### ISSUE TITLE
Avenir du projet et mise à jour ?

### ISSUE THREAD

**Issue by lesamarien** [aymhce/diasporadocker_ynh#12]
Bonjour

je souhaiterais savoir si le projet a été abandonné. Diaspora est passé en 0.7.6.0 mais la mise à jour n'a pas été faites et tous mes messages sont restés sans réponse. J'ai donc pas la possibilité d'utiliser Diaspora sur mon YunoHost.

Merci encore pour ce que tu fais.

**Comment by aymhce** [comment]
Bonjour, désolé pour mon absence (cause de ma situation pro). Le projet n'est pas abandonné, je reviendrai dessus quand j'aurai plus de dispo.

**Comment by aymhce** [comment]
Passage en v 0.7.7.1

**Comment by lesamarien** [comment]
Bonjour @aymhce et merci d'avoir mis la dernière version de Diaspora
J'ai installé 2 version de Diaspora avec adresses différentes (une avant d'avoir acheté un nouveau nom de domaine) mais je souhaite en supprimer une. Est-ce que je peux le faire à partir de Yunohost ? En le faisant, est-ce que ça va pas désinstaller les deux installations ?

Merci de ton aide
