### ISSUE TITLE
Mise à jour vers la version 0.8.0.0

### ISSUE THREAD

**Issue by lesamarien** [aymhce/diasporadocker_ynh#13]
Bonjour

Savez-vous quand vous pourrez mettre à jour Diaspora. Apparemment on est limité à 4.2M pour le téléchargement de photos. La version 0.8.0.0 introduit un rééchantillonnage automatique des fichiers d’image de plus de 4 Mo côté client. Ce qui est interessant.

Merci d'avance

**Comment by aymhce** [comment]
Bonjour, l'application Diaspora pour Yunohost se base sur une images docker produite par [Koehn](https://hub.docker.com/r/koehn/diaspora). Il n'a pas encore sorti de version 0.8.0.0
