### ISSUE TITLE
Mise à jour vers la version 0.7.9.0

### ISSUE THREAD

**Issue by lesamarien** [aymhce/diasporadocker_ynh#14]
Bonjour

La mise à jour 0.7.9.0 est sortie. Pourras tu quand tu auras le temps faire la mise à jour afin qu'on puisse le faire de notre côté.
Malheureusement, je ne suis pas développeur et je ne peux pas t'aider. Bien dommage
Mais peut être que je vais m'y mettre bientôt.

Merci en tout cas pour le taf que tu fais pour nous...

Manu

**Comment by aymhce** [comment]
done

**Comment by lesamarien** [comment]
thank you so much
