### ISSUE TITLE
How to install this version of Diaspora ?

### ISSUE THREAD

**Issue by lesamarien** [aymhce/diasporadocker_ynh#5]
Bonjour
Excusez mon ignorance mais est-ce que l'on doit installer Docker avant d'installer cette version de Diaspora
Désolé, mais je ne suis pas un spécialiste de docker
Merci de votre aide

Hello
Excuse my ignorance but should we install Docker before installing this version of Diaspora?
Sorry, but I'm not a docker specialist
Thank you for your help

**Comment by aymhce** [comment]
Bonjour, pas besoin de pré-installer docker. L'application diaspora s'en charge si il n'est pas déjà installé.

Hello, no need to pre-install docker. The diaspora application does this if it is not already installed.

**Comment by lesamarien** [comment]
Bonjour
Dès que je veux installer Diaspora, j'ai ce message :
"sorry, waiting 300s for startup
docker/run.sh: ligne 11: /usr/local/bin/docker-compose: Permission non accordée"

Hello
As soon as I want to install Diaspora, I have this message:
"sorry, waiting for 300s for startup
docker / run.sh: line 11: / usr / local / bin / docker-compose: Permission not granted"

**Comment by lesamarien** [comment]
Après les 300 secondes, l'installation a continué mais je suis bloqué après ces lignes :
La configuration de SSOwat a été générée
La configuration de SSOwat a été générée
+ yunohost app ssowatconf
+ dockerapp_ynh_reloadservices
+ sudo systemctl reload nginx
+ echo '/etc/nginx/conf.d/mondomaine.fr.d/diasporadocker.conf wasn'\''t deleted because it doesn'\''t exist.'
+ '[' -e /etc/nginx/conf.d/mondomaine.fr.d/diasporadocker.conf ']'
+ [[ f = \/ ]]
Rien ne se passe ensuite et le domaine ne se dirige pas vers mondomaine.fr mais vers yunohost
Merci de votre aide


After 300 seconds, the installation continued but I am stuck after these lines:
The configuration of SSOwat was generated
The configuration of SSOwat was generated
+ yunohost app ssowatconf
+ dockerapp_ynh_reloadservices
+ sudo systemctl reload nginx
+ echo '/etc/nginx/conf.d/mydomain.fr.d/diasporadocker.conf was not deleted because it does not exist.
+ '[' -e /etc/nginx/conf.d/mydomain.fr.d/diasporadocker.conf ']'
+ [[f = \ /]]
Nothing happens next and the domain does not go to mydomain.com but to yunohost
Thank you for your help

**Comment by lesamarien** [comment]
Bonjour

L'installation a réussi la seconde fois. Le soucis était un droit sur le dossier bin
