### ISSUE TITLE
Updated to 0.7.5.0

### ISSUE THREAD

**Issue by lesamarien** [aymhce/diasporadocker_ynh#9]
Bonjour
J'ai voulu faire la mise à jour vers la version 0.7.5.0 avec la commande : docker pull koehn/diaspora et j'ai redémarrer docker mais cela ne fonctionne pas. Je reste en 0.7.4.1
Comment peut-on faire la mise à jour avec docker ?
Merci de votre aide

Hello
I wanted to upgrade to version 0.7.5.0 with the command: docker pull koehn/diaspora and I restart docker but it does not work. I stay in 0.7.4.1
How can we update with docker?
Thank you for your help

**Comment by aymhce** [comment]
@lesamarien image updated on master ! You have to upgrade diasporadocker_app

**Comment by lesamarien** [comment]
Sorry but I'm not a docker pro
How to update the master

Désolé mais je ne suis pas un pro de docker
Comment mettre à jour le master

**Comment by aymhce** [comment]
you can do this
``yunohost app upgrade diasporadocker -u https://github.com/aymhce/diasporadocker_ynh``
it should work for you

**Comment by lesamarien** [comment]
Thank you
And did you see for my other two problems?

Merci
Et avez-vous pu voir pour mes deux autres problèmes ?
